version: 2.1

jobs:
  build:
    docker:
      - image: cypress/base:14

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Run Cypress tests
      - run:
          name: Run Cypress Tests
          command: npm run cy:run