version: 2.1

jobs:
  build:
    docker:
      - image: cimg/cypress:13.4.0

    steps:
      - checkout # Check out your code repository
      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Run Cypress Tests
          command: npx cypress run

      - store_test_results:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  build-and-test:
    jobs:
      - build