version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.05

    steps:
      - checkout # Check out your code repository
      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Run Cypress Tests
          command: npm test

      - store_test_results:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
