version: 2.1

jobs:
  build:
    docker:
      - image: cypress/base:16

    steps:
      - checkout # Check out your code repository
      - setup_remote_docker:
            version: 18.16.0 # Use the desired version of Node.js
      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Run Cypress Tests
          command: npm test


workflows:
  version: 2
  build-and-test:
    jobs:
      - build
