version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:14
    steps:
      - checkout
      - run:
        name: Install Dependencies
        command: npm install
      - run:
          name: Run Cypress Tests
          command: npm run test